stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE: gitlab.sorewa.ru:5050/niaz/subscribe-middleware-go
build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
  only:
    - main

deploy:
  stage: deploy
  script:
    - apk add --no-cache openssh sshpass
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
      cd /root/subscribe-middleware-go &&
      git pull &&
      docker compose pull &&
      docker compose up -d
      "
  only:
    - main