# is deprecated
# version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "56792:56792"
    restart: unless-stopped
    volumes:
      - ./storage:/app-data/storage
    environment:
      - DATABASE_PATH=/app/storage/catalog.db
      - UID=1000
      - GID=1000
volumes:
  storage: