# is deprecated
# version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "56792:56792"
    volumes:
      - ./storage:/app-data/storage
    environment:
      - DATABASE_PATH=/app/storage/catalog.db

volumes:
  storage: